// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  useLessReactDocsSidebar: [
    'use-less-react/intro',
    'use-less-react/getting-started',
    {
      type: 'category',
      label: 'API',
      items: [
        { 
          type: 'autogenerated',
          dirName: "use-less-react/api"
        }
      ]
    },
    'use-less-react/faq',
  ],
};

export default sidebars;
